### ISSUE TITLE
Create CI Pipeline

### ISSUE THREAD

**Issue by fawcilize** [spautz/parameterized-selectors#2]
```
As a contributor
I want a CI pipeline
So that automated tests and linting can be run
And the release process can be streamlined
```

Acceptance Criteria:
- The automation script should run `npm test` and `npm run lint`
- The automation script should allow publishing to npm when given the correct flag

**Comment by mcherryleigh** [comment]
`The automation script should allow publishing to npm when given the correct flag`

While this is definitely possible in Travis I'd recommend working to add it after we've seen a simpler build pass. The pull request I submitted deliberately ignores publishing.
